[remote]
host = "192.168.1.1"
port = 22
user = "user"
agent = true
privatekeyfile = "" # Not needed with agent=true
knownhosts = false # Set to false and provide key below if it failes to find it...
knownhost = "ssh-rsa AAAAB3NzaC1yc2EA...+M7Q=="

[[tail]]
disable=true
output = "messages"
src = "/var/log/messages"

[[pipe]]
output = "dmesg.log"
cmd = ["dmesg", "-Tw"]

[[pipe]]
output = "journal.log"
cmd = ["journalctl", "-ef"]
